import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Column, PageBreak, Row, sone, Text } from "../../src/node.ts";

const dir = path.dirname(fileURLToPath(import.meta.url));

// ── Palette ──────────────────────────────────────────────────────────────────
const INK = "#0f172a";
const MUTED = "#64748b";
const ACCENT = "#2563eb";
const RULE = "#e2e8f0";
const HEADER_BG = "#1e3a5f";
const FOOTER_BG = "#f1f5f9";

// ── Repeating header (appears on every page) ──────────────────────────────────
const header = Row(
  Column(
    Text("MERIDIAN INVOICE SYSTEM").size(13).weight("bold").color("white"),
    Text("Automated billing — Confidential")
      .size(10)
      .color("rgba(255,255,255,0.6)"),
  ).gap(2),
  Text("DRAFT")
    .size(11)
    .weight("bold")
    .color("rgba(255,255,255,0.5)")
    .alignSelf("center"),
)
  .bg(HEADER_BG)
  .padding(12, 24)
  .justifyContent("space-between")
  .alignItems("center");

// ── Repeating footer (appears on every page) ──────────────────────────────────
const footer = Row(
  Text("Meridian Corp — All rights reserved").size(10).color(MUTED),
  Text("Generated by Sone · atlas-meridian.com").size(10).color(MUTED),
)
  .bg(FOOTER_BG)
  .padding(10, 24)
  .justifyContent("space-between")
  .borderWidth(1, 0, 0, 0)
  .borderColor(RULE);

// ── Helpers ───────────────────────────────────────────────────────────────────
const divider = () => Row().height(1).bg(RULE).alignSelf("stretch");

const sectionHeading = (label: string) =>
  Text(label).size(14).weight("bold").color(INK).marginBottom(4);

const bodyText = (t: string) =>
  Text(t).size(13).color("#334155").lineHeight(1.6);

const kv = (label: string, value: string, valueColor = INK) =>
  Row(
    Text(label).size(12).color(MUTED).width(160).shrink(0),
    Text(value).size(12).weight("bold").color(valueColor).shrink(1),
  ).alignItems("flex-start");

// ── Invoice header card ───────────────────────────────────────────────────────
const invoiceCard = Column(
  Row(
    Column(
      Text("INVOICE").size(24).weight("bold").color(ACCENT),
      Text("#INV-2025-00842").size(13).color(MUTED).marginTop(2),
    ).gap(2),
    Column(
      kv("Date", "March 28, 2025"),
      kv("Due date", "April 27, 2025"),
      kv("Status", "UNPAID", "#dc2626"),
    ).gap(6),
  ).justifyContent("space-between"),
)
  .bg("white")
  .padding(20, 24)
  .borderWidth(1)
  .borderColor(RULE);

// ── Parties ───────────────────────────────────────────────────────────────────
const parties = Row(
  Column(
    Text("BILLED BY").size(10).weight("bold").color(MUTED).marginBottom(6),
    Text("Atlas Meridian Corporation").size(13).weight("bold").color(INK),
    Text("1 Meridian Plaza, Floor 12").size(12).color(MUTED),
    Text("New York, NY 10004").size(12).color(MUTED),
    Text("billing@atlas-meridian.com").size(12).color(ACCENT),
  )
    .gap(2)
    .flex(1),
  Column(
    Text("BILLED TO").size(10).weight("bold").color(MUTED).marginBottom(6),
    Text("Nova Systems GmbH").size(13).weight("bold").color(INK),
    Text("Unter den Linden 77").size(12).color(MUTED),
    Text("10117 Berlin, Germany").size(12).color(MUTED),
    Text("accounts@nova-systems.de").size(12).color(ACCENT),
  )
    .gap(2)
    .flex(1),
)
  .bg("white")
  .padding(20, 24)
  .gap(16)
  .borderWidth(1)
  .borderColor(RULE);

// ── Line items table ──────────────────────────────────────────────────────────
const tableHeader = Row(
  Text("Description").size(11).weight("bold").color(MUTED).flex(1),
  Text("Qty").size(11).weight("bold").color(MUTED).width(50).shrink(0),
  Text("Unit Price").size(11).weight("bold").color(MUTED).width(90).shrink(0),
  Text("Amount").size(11).weight("bold").color(MUTED).width(90).shrink(0),
)
  .padding(8, 12)
  .bg("#f8fafc");

const lineItems: [string, string, string, string][] = [
  ["Enterprise SaaS Subscription — Q2 2025", "1", "$18,500.00", "$18,500.00"],
  [
    "Professional Services — API Integration (40 hrs)",
    "40",
    "$195.00",
    "$7,800.00",
  ],
  [
    "Cloud Infrastructure — Dedicated Cluster (3 mo)",
    "3",
    "$2,400.00",
    "$7,200.00",
  ],
  ["Priority Support Package — Gold Tier", "1", "$2,100.00", "$2,100.00"],
  ["Security Audit & Compliance Review", "1", "$4,800.00", "$4,800.00"],
  ["Training Workshop — Remote (2 days)", "2", "$1,250.00", "$2,500.00"],
  ["Custom Reporting Module — Development", "1", "$6,600.00", "$6,600.00"],
  ["SSO Integration — SAML 2.0 Setup", "1", "$1,950.00", "$1,950.00"],
  ["Data Migration — Historical Records Import", "1", "$3,300.00", "$3,300.00"],
  ["Dedicated Account Manager — Annual", "1", "$5,400.00", "$5,400.00"],
];

const rows = lineItems.flatMap(([desc, qty, unit, amt], i) => [
  Row(
    Text(desc).size(12).color(INK).flex(1).lineHeight(1.4),
    Text(qty).size(12).color(MUTED).width(50).shrink(0),
    Text(unit).size(12).color(MUTED).width(90).shrink(0),
    Text(amt).size(12).weight("bold").color(INK).width(90).shrink(0),
  )
    .padding(9, 12)
    .bg(i % 2 === 0 ? "white" : "#fafafa"),
  divider(),
]);

const totalsSection = Column(
  Row(
    Text("Subtotal").size(12).color(MUTED).flex(1),
    Text("$60,150.00").size(12).weight("bold").color(INK),
  ).padding(8, 12),
  divider(),
  Row(
    Text("VAT (19%)").size(12).color(MUTED).flex(1),
    Text("$11,428.50").size(12).weight("bold").color(INK),
  ).padding(8, 12),
  divider(),
  Row(
    Text("TOTAL DUE").size(13).weight("bold").color(INK).flex(1),
    Text("$71,578.50").size(13).weight("bold").color(ACCENT),
  )
    .padding(10, 12)
    .bg("#eff6ff"),
);

const lineItemsSection = Column(
  sectionHeading("Line Items"),
  Column(tableHeader, divider(), ...rows, totalsSection)
    .borderWidth(1)
    .borderColor(RULE),
)
  .bg("white")
  .padding(20, 24)
  .gap(12)
  .borderWidth(1)
  .borderColor(RULE);

// ── Explicit page break ───────────────────────────────────────────────────────
// Forces a new page regardless of where the previous content ended
const explicitBreak = PageBreak();

// ── Payment instructions ──────────────────────────────────────────────────────
const paymentSection = Column(
  sectionHeading("Payment Instructions"),
  Column(
    kv("Bank name", "Deutsche Bank AG"),
    divider(),
    kv("IBAN", "DE89 3704 0044 0532 0130 00"),
    divider(),
    kv("BIC / SWIFT", "DEUTDEDB"),
    divider(),
    kv("Account holder", "Atlas Meridian Corporation"),
    divider(),
    kv("Reference", "INV-2025-00842"),
  )
    .borderWidth(1)
    .borderColor(RULE),
  bodyText(
    "Please include the invoice reference number in the payment description. " +
      "International transfers may take 3–5 business days. " +
      "For faster settlement, SEPA Credit Transfer is available within the SEPA zone.",
  ),
)
  .bg("white")
  .padding(20, 24)
  .gap(12)
  .borderWidth(1)
  .borderColor(RULE);

// ── Terms ─────────────────────────────────────────────────────────────────────
const termsSection = Column(
  sectionHeading("Terms & Conditions"),
  bodyText(
    "1. Payment is due within 30 days of invoice date. Late payments are subject to " +
      "a 1.5% monthly interest charge per the Master Services Agreement (MSA) dated " +
      "January 15, 2024.",
  ),
  bodyText(
    "2. All amounts are quoted in United States Dollars (USD). Currency conversion " +
      "is the responsibility of the payer. Atlas Meridian Corporation is not liable " +
      "for any FX losses incurred during transfer.",
  ),
  bodyText(
    "3. Disputes must be raised in writing within 14 calendar days of receipt of " +
      "this invoice. Undisputed portions remain due on the original due date.",
  ),
  bodyText(
    "4. Services rendered under this invoice are subject to the terms of the Master " +
      "Services Agreement and applicable Order Forms. Copies available on request.",
  ),
  Row(
    Text("Authorised signatory: ________________")
      .size(12)
      .color(MUTED)
      .flex(1),
    Text("Date: ________________").size(12).color(MUTED).width(180).shrink(0),
  ).marginTop(16),
)
  .bg("white")
  .padding(20, 24)
  .gap(10)
  .borderWidth(1)
  .borderColor(RULE);

// ── Root document ─────────────────────────────────────────────────────────────
const root = Column(
  invoiceCard,
  parties,
  lineItemsSection,
  explicitBreak,
  paymentSection,
  termsSection,
)
  .width(720)
  .bg("#f8fafc")
  .gap(2);

// ── Render pages ──────────────────────────────────────────────────────────────
const PAGE_HEIGHT = 900;
const pages = await sone(root, {
  pageHeight: PAGE_HEIGHT,
  header,
  footer,
}).pages();

for (let i = 0; i < pages.length; i++) {
  const buf = await pages[i].toBuffer("jpg", { density: 1 });
  const outPath = path.join(dir, `pages-2-p${i + 1}.jpg`);
  await fs.writeFile(outPath, buf);
  console.log(
    `  page ${i + 1}: ${pages[i].width}×${pages[i].height}  →  ${outPath}`,
  );
}

console.log(`\nTotal: ${pages.length} pages`);
