/**
 * Visual test: multi-language code document rendered as PDF
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Column, Row, sone, Text } from "../../src/node.ts";
import { createSoneHighlighter } from "../../src/shiki.ts";
import { loadVisualTestFonts } from "./load-test-fonts.ts";

await loadVisualTestFonts();

const dir = path.dirname(fileURLToPath(import.meta.url));

// ── Page geometry ─────────────────────────────────────────────────────────────
const PAGE_H = 1123; // A4 @ 96 dpi
const PAGE_W = 794;
const MARGIN = 56;
// ── Palette ───────────────────────────────────────────────────────────────────
const INK = "#111827";
const SUB = "#6b7280";
const RULE = "#e5e7eb";
const MONO = ["GeistMono"];
const SANS = ["GeistMono"]; // use same font family for this test

const highlight = await createSoneHighlighter({
  themes: ["github-dark", "github-light"],
  langs: ["typescript", "python", "bash"],
});

// ── Section helpers ───────────────────────────────────────────────────────────
function SectionHeading(title: string) {
  return Column(
    Text(title)
      .font(...SANS)
      .size(15)
      .weight("bold")
      .color(INK),
    Column().height(1).bg(RULE).marginTop(6),
  ).gap(0);
}

function Prose(...lines: string[]) {
  return Text(lines.join(" "))
    .font(...SANS)
    .size(12)
    .color(SUB)
    .lineHeight(1.6);
}

function CodeBlock(
  code: string,
  lang: Parameters<typeof highlight.Code>[1]["lang"],
  theme: "github-dark" | "github-light" = "github-dark",
) {
  return highlight
    .Code(code, {
      lang,
      theme,
      fontSize: 11,
      fontFamily: MONO,
      lineHeight: 1.55,
      paddingX: 14,
      paddingY: 10,
    })
    .borderRadius(6)
    .overflow("hidden");
}

// ── Content ───────────────────────────────────────────────────────────────────
const page = Column(
  // Title block
  Column(
    Text("Sone + Shiki")
      .font(...SANS)
      .size(28)
      .weight("bold")
      .color(INK),
    Text("Syntax-highlighted code in PDF documents")
      .font(...SANS)
      .size(13)
      .color(SUB)
      .marginTop(4),
    Row(
      Text("sone/shiki")
        .font(...MONO)
        .size(11)
        .color("#6b7280"),
      Text("•")
        .font(...SANS)
        .size(11)
        .color(RULE),
      Text("github-dark / github-light")
        .font(...MONO)
        .size(11)
        .color("#6b7280"),
    )
      .gap(8)
      .marginTop(8),
  ).gap(0),

  // Section 1 — TypeScript
  SectionHeading("1. TypeScript"),
  Prose(
    "Use",
    "createSoneHighlighter()",
    "to pre-load themes and languages.",
    "Each call to",
    "Code()",
    "returns a Sone ColumnNode ready to embed in any layout.",
  ),
  CodeBlock(
    `\
import { createSoneHighlighter } from "sone/shiki"

const highlight = await createSoneHighlighter({
  themes: ["github-dark"],
  langs: ["typescript", "javascript"],
})

const block = highlight.Code(\`const greet = (name: string) => \\\`Hello, \${name}!\\\`\`, {
  lang: "typescript",
  fontSize: 13,
  fontFamily: ["monospace"],
})`,
    "typescript",
    "github-dark",
  ),

  // Section 2 — Python
  SectionHeading("2. Python"),
  Prose(
    "The same highlighter supports any language bundled with Shiki.",
    "Here is a Python example using github-light theme.",
  ),
  CodeBlock(
    `\
from dataclasses import dataclass
from typing import Optional

@dataclass
class User:
    id: int
    name: str
    email: Optional[str] = None

def fetch_user(user_id: int) -> User:
    data = api.get(f"/users/{user_id}")
    return User(**data)`,
    "python",
    "github-light",
  ),

  // Section 3 — Shell
  SectionHeading("3. Shell"),
  Prose("Build and run the visual tests from the project root:"),
  CodeBlock(
    `\
# Install dependencies
npm install

# Build the library
npm run build

# Run all tests
npm test

# Generate visual regression outputs
npx tsx test/run-visual.ts`,
    "bash",
    "github-dark",
  ),

  // Footer
  Column().flex(1),
  Column(
    Column().height(1).bg(RULE),
    Row(
      Text("Generated by Sone")
        .font(...MONO)
        .size(10)
        .color(SUB),
      Text("sone/shiki integration")
        .font(...MONO)
        .size(10)
        .color(SUB),
    )
      .justifyContent("space-between")
      .marginTop(8),
  ),
)
  .gap(20)
  .padding(MARGIN)
  .width(PAGE_W);

const pdf = await sone(page, { pageHeight: PAGE_H }).pdf();
await fs.writeFile(path.join(dir, "shiki-2.pdf"), pdf);
console.log("wrote shiki-2.pdf");
